apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: remote-skeleton-retaining
  title: Remote File Template
  description: Remote Retaining Of Skeleton
  tags:
    - text
    - discovery
    - backstage
    - remote
spec:
  owner: service@example.com
  type: service

  parameters:
    - title: Provide some simple information
      required:
        - filename
      properties:
        filename:
          title: Filename
          type: string
          description: Our remote txt file will be named by this value
        remoteInserting:
          title: First Value To Replace
          type: string
          description: This Value Will Be Inserted Into The Linked Place
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: https://github.com/VanushAtanian/backstage-remote-skeleton/tree/main/skeleton
        values:
          filename: ${{ parameters.filename }}
          remoteInserting: ${{ parameters.remoteInserting }}

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ["github.com"]
        description: This is ${{ parameters.filename }} repository
        repoUrl: ${{ parameters.repoUrl }}

    - id: register
      name: Register
      action: debug:log
      input:
        message: ${{ steps['publish'].output.remoteUrl }}
